#!/usr/bin/env bash
# alias

# tui
alias tg='lazygit'
alias td='lazydocker'
alias tq='lazysql'
alias ij='zellij'
alias sc='scooter'

# ls
alias ls='lsd'
alias ll='lsd -l'
alias la='lsd -lA'

# bat
alias cat='bat --paging=never'

# pnpm
alias ppm='pnpm'

# grsync
alias rr='grsync --exclude-dir=.git -a'

# alias ends here
